version: '3.8'
services:
  mysql:
    image: mysql:8.1
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokemon_world
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
